### ISSUE TITLE
stm32h743xx.h: wrong definition of FLASH_CRCCR_ALL_BANK_Pos

### ISSUE THREAD

**Issue by deadror** [STMicroelectronics/cmsis_device_h7#1] opened 2020-05-06 12:16 UTC
The **FLASH_CRCCR_ALL_BANK_Pos** definition is set to 22.
According to the RM0433 Rev 7 (February 2020), the ALL_BANK bit in FLASH_CRCCR1 is bit 7.
The correct value for FLASH_CRCCR_ALL_BANK_Pos should be:

`#define FLASH_CRCCR_ALL_BANK_Pos             (7U)`

**Comment by ASELSTM** [comment] 2020-05-13 11:13
Hi @deadror ,

Thank you for your contribution.

We raised this issue to our development teams, and they confirmed that the ALL_BANK bit is defined at bit 22 instead of bit 7. 

Indeed, the ALL_BANK bit in CUT1.0 has indeed been defined at bit 7, and it has been moved to bit 22 in the new CUT2.0. So, the problem is rather related to the documentation. 

In fact, this version of the reference manual is not yet updated with the new position of the ALL_BANK bit in the CUT2.0 of the STM32H7 which is bit 22. However, this is in progress. The RM0433 is being updated, the ALL_BANK bit position will be fixed and the new version of the reference manual will be available at a later date.

Since that the issue is not related to the CMSIS device, allow me to close this issue, thank you for your comprehension.

With regards,

**Closed** 2020-05-14 08:56 UTC
